language: node_js
node_js:
  - "6"
install:
  - npm install
  - npm install -g codecov
  - npm install -g mocha
script:
  - NODE_ENV=test ISINTEGERISH_COVERAGE=1 mocha --require blanket --reporter mocha-lcov-reporter
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)